version: '3'

volumes:
  postgres_ab:

services:
  postgres:
    image: postgres
    volumes:
      - postgres_ab:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: account_balance
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432