version: '3'

volumes:
  postgres_ce:

services:
  postgres:
    image: postgres
    volumes:
      - postgres_ce:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: currency_exchange
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432