server:
  port: 8300

spring:
  application:
    name: currency-exchange-service

  datasource:
    url: jdbc:postgresql://localhost:5433/currency_exchange
    username: admin
    password: password

  jpa:
    hibernate:
      ddl-auto: update

freecurrency:
  uri: http://api.exchangeratesapi.io/v1/
  apikey: e5189870d0b81c26ad73005a8009b77b

exchange:
  update:
    interval: 86400